### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by kwonej0617** [bartongroup/yanocomp#11]
Hi! Thank you for developing a useful tool!
I want to run yanocomp. After installation based on your instruction, I run `yanocomp prep -help` to see if the installation was successfully done. However, I got the error message as follows. 
````
(base) [euijin.kwon-umw@c6525c12 yanocomp]$ conda activate yanocomp
(yanocomp) [euijin.kwon-umw@c6525c12 yanocomp]$ yanocomp prep --help
Traceback (most recent call last):
  File "/home/euijin.kwon-umw/miniconda3/envs/yanocomp/bin/yanocomp", line 5, in <module>
    from yanocomp.cli import cli
  File "/home/euijin.kwon-umw/miniconda3/envs/yanocomp/lib/python3.9/site-packages/yanocomp/cli.py", line 9, in <module>
    from .prep import nanopolish_collapse
  File "/home/euijin.kwon-umw/miniconda3/envs/yanocomp/lib/python3.9/site-packages/yanocomp/prep.py", line 13, in <module>
    from .io import parse_eventalign, load_gtf_database, save_events_to_hdf5
  File "/home/euijin.kwon-umw/miniconda3/envs/yanocomp/lib/python3.9/site-packages/yanocomp/io.py", line 13, in <module>
    import h5py as h5
  File "/home/euijin.kwon-umw/miniconda3/envs/yanocomp/lib/python3.9/site-packages/h5py/__init__.py", line 46, in <module>
    from ._conv import register_converters as _register_converters
  File "h5py/_conv.pyx", line 1, in init h5py._conv
  File "h5py/h5t.pyx", line 293, in init h5py.h5t
  File "/home/euijin.kwon-umw/miniconda3/envs/yanocomp/lib/python3.9/site-packages/numpy/__init__.py", line 320, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'typeDict'
````
I tried installation with `pip install git+git://github.com/bartongroup/yanocomp.git`. but it also didn't work. Could you please help me?

Thank you!!

**Comment by kwonej0617** [comment]
I fixed the issue. After activating yanocomp conda env, I run, `conda install numpy==1.21`.

Best,
Euijin
